### ISSUE TITLE
dashes in existing frontmatter in source HTML files become escaped.

### ISSUE THREAD

**Issue by schneidr** [JohannesKaufmann/html-to-markdown#26]
**Describe the bug**

dashes in existing frontmatter in source HTML files become escaped.

**HTML Input**
```yaml
---
type: page
layout: reisebericht
title: Hamar
date: '2018-10-24 22:32:03 +0100'
weight: 2
tags:
- Norwegen
- Hamar
url: /2018/10-norwegen/02-hamar/
description: Ein Spaziergang durch Hamar, Shoppen und ein Besuch im Norsk jernbanemusem, dem norwegischen Eisenbahnmuseum.
image: files/2018/10-Norwegen/Hamar_Titel.jpg
---
```

**Generated Markdown**
````yaml
\-\-\-
type: page
layout: reisebericht
title: Hamar
date: '2018-10-24 22:32:03 +0100'
weight: 2
tags:
\- Norwegen
\- Hamar
url: /2018/10-norwegen/02-hamar/
description: Ein Spaziergang durch Hamar, Shoppen und ein Besuch im Norsk jernbanemusem, dem norwegischen Eisenbahnmuseum.
image: files/2018/10-Norwegen/Hamar\_Titel.jpg
\-\-\-
````

**Expected Markdown**
````yaml
---
type: page
layout: reisebericht
title: Hamar
date: '2018-10-24 22:32:03 +0100'
weight: 2
tags:
- Norwegen
- Hamar
url: /2018/10-norwegen/02-hamar/
description: Ein Spaziergang durch Hamar, Shoppen und ein Besuch im Norsk jernbanemusem, dem norwegischen Eisenbahnmuseum.
image: files/2018/10-Norwegen/Hamar_Titel.jpg
---
````

**Additional context**
This problem occurs when the source files already contain frontmatter (for example when converting Hugo .html files to .md).
